{% set name = "httpx-sse" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/httpx-sse-{{ version }}.tar.gz
  sha256: 1e81a3a3070ce322add1d3529ed42eb5f70817f45ed6ec915ab753f961139721

build:
  # nothing provides h2 3.* needed by httpcore on s390x
  skip: True  # [py<38 or s390x]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python
    - httpx

test:
  imports:
    - httpx_sse
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Consume Server-Sent Event (SSE) messages with HTTPX.
  description: |
    httpx-sse provides the connect_sse and aconnect_sse helpers for connecting to an SSE endpoint.
    The resulting EventSource object exposes the .iter_sse() and .aiter_sse() methods to iterate over the server-sent events.
  home: https://github.com/florimondmanca/httpx-sse
  license: MIT
  license_file: LICENSE
  license_family: MIT
  doc_url: https://github.com/florimondmanca/httpx-sse
  dev_url: https://github.com/florimondmanca/httpx-sse

extra:
  recipe-maintainers:
    - jan-janssen
